### ISSUE TITLE
unableto do speed test anymore. also some warning s ?unlinked

### ISSUE THREAD

**Issue by AbuYahyaa** [hkuchampudi/Windscribe#1]
during connecting i get these three warnings but connects ok. speed is a bit slower than previously. If i run speedtest stays on 0 . log doesnt show anything for that other than speedtest requested and then aborted

> `WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Tue Jan 16 18:59:49 2018 WARNING: file '/etc/windscribe/credentials.txt' is group or others accessible
Tue Jan 16 18:59:49 2018 OpenVPN 2.4.4 x86_64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Tue Jan 16 18:59:49 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.10
Tue Jan 16 18:59:49 2018 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Tue Jan 16 18:59:49 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jan 16 18:59:49 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:49 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:49 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:49 2018 UDP link local: (not bound)
Tue Jan 16 18:59:49 2018 UDP link remote: [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:49 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jan 16 18:59:49 2018 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
Tue Jan 16 18:59:49 2018 VERIFY OK: nsCertType=SERVER
Tue Jan 16 18:59:49 2018 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Tue Jan 16 18:59:50 2018 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Tue Jan 16 18:59:50 2018 [Windscribe Node Server 4096] Peer Connection Initiated with [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:51 2018 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Tue Jan 16 18:59:51 2018 Outgoing Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:51 2018 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Tue Jan 16 18:59:51 2018 Incoming Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:51 2018 TUN/TAP device tun0 opened
Tue Jan 16 18:59:51 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Jan 16 18:59:51 2018 /usr/bin/ip link set dev tun0 up mtu 1500
WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6
Tue Jan 16 18:59:49 2018 WARNING: file '/etc/windscribe/credentials.txt' is group or others accessible
Tue Jan 16 18:59:49 2018 OpenVPN 2.4.4 x86_64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep 26 2017
Tue Jan 16 18:59:49 2018 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.10
Tue Jan 16 18:59:49 2018 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.
Tue Jan 16 18:59:49 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Tue Jan 16 18:59:49 2018 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:49 2018 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:49 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:49 2018 UDP link local: (not bound)
Tue Jan 16 18:59:49 2018 UDP link remote: [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:49 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Tue Jan 16 18:59:49 2018 VERIFY OK: depth=1, C=CA, ST=ON, L=Toronto, O=Windscribe Limited, OU=Operations, CN=Windscribe Node CA
Tue Jan 16 18:59:49 2018 VERIFY OK: nsCertType=SERVER
Tue Jan 16 18:59:49 2018 VERIFY OK: depth=0, C=CA, ST=ON, O=Windscribe Limited, OU=Operations, CN=Windscribe Node Server 4096
Tue Jan 16 18:59:50 2018 Control Channel: TLSv1.2, cipher TLSv1.2 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
Tue Jan 16 18:59:50 2018 [Windscribe Node Server 4096] Peer Connection Initiated with [AF_INET]89.238.131.131:443
Tue Jan 16 18:59:51 2018 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
Tue Jan 16 18:59:51 2018 Outgoing Data Channel: Using 512 bit message hash 'SHA512' for HMAC authentication
Tue Jan 16 18:59:51 2018 TUN/TAP device tun0 opened
Tue Jan 16 18:59:51 2018 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
Tue Jan 16 18:59:51 2018 /usr/bin/ip link set dev tun0 up mtu 1500`

are the warnings possible security lapses?
any ideas why the cli speetest functioon not working

**Comment by hkuchampudi** [comment]
@AbuYahyaa 

Sorry, it is a little difficult to read through the log you provided without proper formatting.

Most of the warnings that OpenVPN is throwing are notices of deprecation (which simply suggest that newer versions of OpenVPN are using newer commands to do similar functions). These OpenVPN warnings should not be a source of concern and might be updated in a later beta release by Windscribe (since we are still on the first beta for Linux).

For the following error ```WARNING: file '/etc/windscribe/credentials.txt' is group or others accessible```, you can change the permissions of the file to 600 and the message should disappear.

As for the speed test issue, I just tried connecting to a server in the UK and noticed that a similar issue appears for me as well where running `windscribe speedtest` sits at 0 Kbit/s. I do not know what is causing this, as other servers do not seem to be experiencing this issue. There may be a networking problem somewhere that is preventing clients from accessing the speed test functionality. You will want to ask Windscribe directly as this is beyond my control. However, I am still able to access the Internet despite the speed test aborting, and running a manual speed test using `wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip` shows that I am getting decent speeds.

**Comment by AbuYahyaa** [comment]
thanks for your feedback. 
speedtest seems to be working today ... and was working on another machine previously... so it may be with specific IPs that it wasnt.

**Comment by yegors** [comment]
Hi, Windscribe dev here. We're working on an update right now, we're hoping to release it in a week or 2. 

Will remove deprecated parameters next week, the applications should pull in a new config when it changes. 

As for the speed tests, we will investigate. We might have messed up the configuration on the newer nodes, as you're testing the speed over the tunnel directly to the server.  Can you post your Windscribe IP at the time of the speed test failure, as it will help us isolate the problematic server(s).

**Comment by hkuchampudi** [comment]
@yegors 

Thanks for the additional clarification. In my case, it was the following node:
```json
{"group": "Manchester - United", "weight": 1, "ip": "89.238.131.130", "hostname": "uk-006.whiskergalaxy.com", "ip2": "89.238.131.131", "ip3": "89.238.131.132", "pro_only": 1}
```
Specifically, the log reports that I was connected to `89.238.131.131`

**Comment by yegors** [comment]
We made some tweaks, it should be resolved.

**Comment by hkuchampudi** [comment]
@yegors 

Thanks for looking into this. After connecting to the same node, `windscribe speedtest` appears to be working. I will go ahead and close this issue.

```
2018-01-22 16:36:01,960 [INFO] Chosen node: {u'group': u'Manchester - United', u'weight': 1, u'ip': u'89.238.131.130', u'hostname': u'uk-006.whiskergalaxy.com', u'ip2': u'89.238.131.131', u'ip3': u'89.238.131.132', u'pro_only': 1}
...
2018-01-22 16:36:07,625 [INFO] command "connect" done
2018-01-22 16:36:17,377 [INFO] Daemon: got command: "speedtest"
2018-01-22 16:38:44,878 [INFO] Speed test done: 6.29 Mb/s
2018-01-22 16:38:44,892 [INFO] command "speedtest" done
2018-01-22 16:38:50,116 [INFO] Daemon: got command: "disconnect"
2018-01-22 16:38:50,116 [INFO] Start Disconnect
2018-01-22 16:38:50,152 [INFO] Firewall: removing rule for ip 89.238.131.131
2018-01-22 16:38:50,181 [INFO] command "disconnect" done
```
