### ISSUE TITLE
windscribe error

### ISSUE THREAD

**Issue by jsotiriou** [hkuchampudi/Windscribe#2]
hi hkuchampudi, 
I am clickit from aur.archlinux and I've read your message there so here I am
I run the 64bit version of Arch linux

The full error message is **"windscribe: error while loading shared libraries: libz.so.1: failed to map segment from shared object"**

It's happening with every windscribe's parameter that I give
 
below is my fstab file 
> 
> UUID=a5448df7-77b6-4344-a1c9-d94427f7872e	/boot     	ext3      noatime,nodiratime,barrier=0	0	0
> UUID=098cae17-e288-41f7-bc09-5bf0f1908af4	/         	ext4      	noatime,nodiratime,barrier=0	0 	0
> UUID=f8adb233-c6d0-49af-9bbd-6e6ce25ce351	/home     	ext4    noatime,nodiratime,barrier=0,noauto,x-systemd.automount		0 	0
> /sTORAGE/swapfile				none 		swap		defaults			0 0
> tmpfs /tmp tmpfs   	noatime,nodiratime,rw,size=500M,nr_inodes=5k,noexec,nodev,nosuid,uid=clickit,gid=clickit,mode=1777 0 0
> tmpfs  /var/tmp tmpfs   	noatime,nodiratime,rw,size=1G,nr_inodes=5k,noexec,nodev,nosuid,uid=clickit,gid=clickit,mode=1777 0 0
> 

btw, I searhed everywhere but I couldn't find windscribe's log file...

thx in advance
jim

p.s.
sorry for my English 
is not my native language

**Comment by hkuchampudi** [comment]
@jsotiriou 
Thanks for posting on here. You should be able to find the log at `/var/log/windscribe/windscribe.log`.

I have not seen this error before, so I am hoping that the log file will tell us more about what is happening.

**Comment by jsotiriou** [comment]
cat: /var/log/windscribe/windscribe.log: No such file or directory

**Comment by hkuchampudi** [comment]
Hmmm, so that the windscribe binary does not even seem to be able to start for long enough to create a log file. I was just searching Google for the error message, and it seems like the most common reason for this error is that there are non-exec permissions on /tmp. In your `fstab` I notice that you are also using `noexec` on `/tmp`. Could you try removing `noexec` and rebooting and trying again?

**Comment by jsotiriou** [comment]
I found solution for the error
**sudo mount /tmp -o remount,exec** 

[edit]
you were right
thx

**Comment by hkuchampudi** [comment]
Yeah, so it was an `exec` mounting problem. Cool, can I go ahead and close this issue?

**Comment by jsotiriou** [comment]
provided solution solved the problem
