### ISSUE TITLE
Getting error while login in on the windscribe

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [hkuchampudi/Windscribe#5]
Hey,
I am currently using Antergos, and I installed windscribe-cli via pamac. I did the `sudo systemctl start windscribe` and tried to `windscribe login` but I am getting this `Error running "login"`. What can it be?
Thanks,
Miguel de Carvalho

**Comment by MiguelNdeCarvalho** [comment]
Now it is giving: `API Error: Could not log in with provided credentials`

**Comment by hkuchampudi** [comment]
That error suggests that you are not logging-in with a valid username and password combination? You should check if you can log-in to your Windscribe account in your browser. 

This does not appear to be an issue with the packaging, and is outside of my purview; you should open a ticket with Windscribe support: https://windscribe.com/support

**Comment by MiguelNdeCarvalho** [comment]
It is solved now, I dont know if it was the network that I was using, that was blocking the login. Thanks anyway. Keep good job
